---
- name: Install Ansible dependencies
  dnf:
    name:
      - firewalld
      - python-firewall
    state: present
- name: Enable firewalld
  service:
    name: firewalld
    enabled: true
    state: started
- name: Apply firewall rules
  firewalld:
    port: '{{ item.port }}/{{ item.proto|default("tcp") }}'
    state: '{{ "enabled" if item.allow|default(true) else "disabled" }}'
    permanent: true
    immediate: true
  with_items: '{{ firewall_rules }}'
