#!/bin/sh
# Copyright 2018 Jordan Geoghegan

# Permission to use, copy, modify, and/or distribute this software for any 
# purpose with or without fee is hereby granted, provided that the above 
# copyright notice and this permission notice appear in all copies.

# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH 
# REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
# AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
# INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM 
# LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE 
# OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR 
# PERFORMANCE OF THIS SOFTWARE.


# Download some of the most popular IP Blocklists, you can add any lists here 
# you like as long as they have similar formatting to the other lists. 

# Make temp folder to hold all files

mkdir /tmp/pfbadhost

# Download popular IP blocklists and parse

cd /tmp/pfbadhost 
ftp https://www.binarydefense.com/banlist.txt
ftp https://rules.emergingthreats.net/blockrules/compromised-ips.txt
ftp https://rules.emergingthreats.net/fwrules/emerging-Block-IPs.txt
ftp https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level3.netset
ftp https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level2.netset
ftp https://raw.githubusercontent.com/firehol/blocklist-ipsets/master/firehol_level1.netset
perl -lne 'print if ! /^\s*(#.*)?$/' *.txt *.netset | sort -uV > pf-badhost.txt

# Block Shodan

ftp https://isc.sans.edu/api/threatlist/shodan/shodan.txt 
egrep -o '([[:digit:]]{1,3}\.){3}[[:digit:]]{1,3}' shodan.txt >> pf-badhost.txt

# Move banlist into /etc and reload the pf table

mv /tmp/pfbadhost/pf-badhost.txt /tmp/
doas cp /tmp/pf-badhost.txt /etc/
doas pfctl -t badhosts -T replace -f /etc/pf-badhost.txt 2> /dev/null

# Clean up after ourselves

rm -r /tmp/pfbadhost
rm /tmp/pf-badhost.txt
